### ISSUE TITLE
no entity despite configuration in home assistant.

### ISSUE THREAD

**Issue by KazadorFR** [spycle/tuneblade#2]
the configuration of the devices is functional but no entity is created. It is therefore impossible to launch the connection on the tuneblade server so that it connects to the selected device.

Reinstallation of the hacs done. Device configuration. starting home assistant. nothing is working right now.

**Comment by KazadorFR** [comment]
I must specify that during a previous configuration everything was functional. the tests were carried out on my main computer. I then created a windows 11 virtual machine under Truenas scale with a pci pass though audio, wifi, and bluethoot devices. Installed tuneblade with a license. Everything is working, and tuneblade can connect to different airplay device. The master volume is activated. Only no switch is added on home assistant when adding the tuneblade device on home assistant.

**Comment by spycle** [comment]
It's been a while since I've used this to be honest but from memory it's not using discovery and won't validate your input. If no entity is created then it's not finding the server. 

If you are using a VM then I suspect the problem is there. Are you specifying the host as something like 192.168.etc and not localhost?

edit: it does validate input

**Comment by KazadorFR** [comment]
Yes, it is directly the target ip address that is entered. Infact here is after inspection the error in question of the logs:

Logger: homeassistant.config_entries
Source: helpers/entity_component.py:166
First occurred: 10:08:49 (4 occurrences)
Last logged: 10:08:50

Error setting up entry 0499B95FCC3C for switch
Error setting up entry 0499B95FCC3C for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/switch/__init__.py", line 83, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 166, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!




As the device id is the same (than the configuration during the previous tests but with a different ip), home assistant encounters a configuration problem, but this entity is no longer visible to be deleted. The factory reset of the device does not change the device id and therefore home assistant is stuck on this step. I worked a few hours on the problem, for the moment impossible to find the previous entities in order to delete it and make them available again for creation.

**Comment by spycle** [comment]
ah ok thanks for the logs, that explains it.

OK I'll fix that. In the mean-time you could try and remove the device record manually from /config/.storage/core.device_registry. Take a backup before messing with that file though

**Comment by KazadorFR** [comment]
great, thank you !. I imagine just adding a series of random letters/numbers to the device id name in the code? Since yesterday I explore the possibility to access the file because it is a hidden file. I found some script in php to delete unused entities but no python or real methodology in this direction.


Thank you for the work, it allows me to do a lot of things!!




EDIT:I found it thanks to your explanation. thank you very much !

EDIT2: After deleting devices, reinstalling tuneblade hacs, deleting entities in "/config/.storage/core.device_registry." Here are the new log errors:




Cette erreur provient d'une intégration personnalisée

Logger: custom_components.tuneblade
Source: custom_components/tuneblade/tuneblade.py:34
Integration: TuneBlade (documentation, issues)
First occurred: 11:41:48 (1 occurrences)
Last logged: 11:41:48

Error fetching information from http://192.168.1.199:49999/devices/94EA32730239 - 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('http://192.168.1.199:49999/devices/94EA32730239')





Logger: homeassistant.components.switch
Source: custom_components/tuneblade/switch.py:30
Integration: Commutateur (documentation, issues)
First occurred: 11:41:49 (2 occurrences)
Last logged: 11:41:49

Error adding entities for domain switch with platform tuneblade
Error while setting up tuneblade platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 438, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 604, in _async_add_entity
    suggested_object_id = entity.name
  File "/config/custom_components/tuneblade/switch.py", line 30, in name
    device = self.coordinator.data.get("Name")
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by KazadorFR** [comment]
after complete reinstallation of home assistant, I also tested on 2 different machines (including the old one which worked) and I have the same error messages in the logs as above. currently stuck at this stage.

**Comment by spycle** [comment]
Did you also remove the master volume device from core.device_registry? Not that that would explain why a fresh install wouldn't work. Might look into this next weekend but I saw from the forum you had a workaround so haven't prioritised
